INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/settings.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 22, in madlib_list
    classes = [name for name in dir(storedMadlibs) if inspect.isclass(getattr(storedMadlibs, name, None))]
NameError: name 'storedMadlibs' is not defined
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/templates/data/StoredMadlibs.py changed, reloading.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 21, in madlib_list
    import StoredMadlibs
ModuleNotFoundError: No module named 'StoredMadlibs'
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /ZooMadLib
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
WARNING:django.request:Not Found: /ZooMadLib
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
WARNING:django.request:Not Found: /ZooMadLib
WARNING:django.request:Not Found: /ZooMadLib
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/urls.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/urls.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/urls.py changed, reloading.
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/urls.py changed, reloading.
ERROR:django.request:Internal Server Error: /ZooMadLib/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 51, in madlib
    klass = getattr(storedMadlibs, madlib_class)
NameError: name 'storedMadlibs' is not defined
INFO:django.utils.autoreload:/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /ZooMadLib/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 80, in madlib
    return render(
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'madlib' with keyword arguments '{'madlib_class': ''}' not found. 1 pattern(s) tried: ['(?P<madlib_class>[^/]+)/\\Z']
ERROR:django.request:Internal Server Error: /ZooMadLib/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 80, in madlib
    return render(
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'madlib' with keyword arguments '{'madlib_class': ''}' not found. 1 pattern(s) tried: ['(?P<madlib_class>[^/]+)/\\Z']
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:django.request:Internal Server Error: /hello/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 90, in madlib
    return render(request, "madlib-exception.html", {"error": error})
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: madlib-exception.html
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:django.request:Internal Server Error: /hello/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 90, in madlib
    return render(request, "madlib-exception.html", {"error": error})
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: madlib-exception.html
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:django.request:Internal Server Error: /hello/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 90, in madlib
    return render(request, "madlib-exception.html", {"error": error})
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: madlib-exception.html
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:django.request:Internal Server Error: /hello/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 90, in madlib
    return render(request, "madlib-exception.html", {"error": error})
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: madlib-exception.html
ERROR:django.request:Internal Server Error: /ZooMadLib/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 80, in madlib
    return render(
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'madlib' with keyword arguments '{'madlib_class': ''}' not found. 1 pattern(s) tried: ['(?P<madlib_class>[^/]+)/\\Z']
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:django.request:Internal Server Error: /hello/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 90, in madlib
    return render(request, "madlib-exception.html", {"error": error})
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: madlib-exception.html
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'base'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'base'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:root:{'type': 'AttributeError', 'message': "module 'madlibs.StoredMadlibs' has no attribute 'hello'"}
ERROR:django.request:Internal Server Error: /ZooMadLib/
Traceback (most recent call last):
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/madlibs/views.py", line 80, in madlib
    return render(
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/troydavidson/CSE310_Projects/dJangoMadLabWebApp/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'madlib' with keyword arguments '{'madlib_class': ''}' not found. 1 pattern(s) tried: ['(?P<madlib_class>[^/]+)/\\Z']
